swagger: "2.0"
info:
  title: AfricasTalking HTTP Listeners
  description: HTTP service for interacting with callbacks supporting AfricasTalking APIs
  termsOfService: https://github.com/wondenge/at-notifiers/blob/master/LICENSE
  contact:
    name: William Ondenge
    email: ondengew@gmail.com
    url: https://www.ondenge.me
  license:
    name: Apache License
    url: https://github.com/wondenge/at-notifiers/blob/master/LICENSE
  version: "1.0"
host: localhost:3000
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /callbacks/africastalking/airtime/status:
    post:
      tags:
      - africastalking
      summary: status_notifier africastalking
      description: Adds new Airtime Status Notification to our callback URL and return its ID.
      operationId: africastalking#status_notifier
      parameters:
      - name: status_notifier_request_body
        in: body
        required: true
        schema:
          $ref: '#/definitions/AfricastalkingStatusNotifierRequestBody'
      responses:
        "201":
          description: Created response.
          schema:
            type: string
      schemes:
      - http
  /callbacks/africastalking/airtime/validation:
    post:
      tags:
      - africastalking
      summary: validation_notifier africastalking
      description: Adds new Airtime Validation Notification to our callback URL and return its ID.
      operationId: africastalking#validation_notifier
      parameters:
      - name: validation_notifier_request_body
        in: body
        required: true
        schema:
          $ref: '#/definitions/AfricastalkingValidationNotifierRequestBody'
      responses:
        "201":
          description: Created response.
          schema:
            $ref: '#/definitions/AfricastalkingValidationNotifierResponseBody'
      schemes:
      - http
  /callbacks/africastalking/iot/events:
    post:
      tags:
      - africastalking
      summary: iot_notifier africastalking
      description: Adds new IoT Notification to our callback URL and return its ID.
      operationId: africastalking#iot_notifier
      parameters:
      - name: iot_notifier_request_body
        in: body
        required: true
        schema:
          $ref: '#/definitions/AfricastalkingIotNotifierRequestBody'
      responses:
        "201":
          description: Created response.
          schema:
            type: string
      schemes:
      - http
  /callbacks/africastalking/payments/b2c/validation:
    post:
      tags:
      - africastalking
      summary: b2c_validation_notifier africastalking
      description: Adds new B2C Validation Notification to our callback URL and return its ID.
      operationId: africastalking#b2c_validation_notifier
      parameters:
      - name: b2c_validation_notifier_request_body
        in: body
        required: true
        schema:
          $ref: '#/definitions/AfricastalkingB2cValidationNotifierRequestBody'
      responses:
        "201":
          description: Created response.
          schema:
            $ref: '#/definitions/AfricastalkingB2cValidationNotifierResponseBody'
      schemes:
      - http
  /callbacks/africastalking/payments/c2b/validation:
    post:
      tags:
      - africastalking
      summary: c2b_validation_notifier africastalking
      description: Adds new C2B Validation Notification to our callback URL and return its ID.
      operationId: africastalking#c2b_validation_notifier
      parameters:
      - name: c2b_validation_notifier_request_body
        in: body
        required: true
        schema:
          $ref: '#/definitions/AfricastalkingC2bValidationNotifierRequestBody'
          required:
          - provider
          - productName
          - phoneNumber
          - value
          - providerMetadata
      responses:
        "201":
          description: Created response.
          schema:
            type: string
      schemes:
      - http
  /callbacks/africastalking/payments/events:
    post:
      tags:
      - africastalking
      summary: payment_notifier africastalking
      description: Adds new Payment Notification to our callback URL and return its ID.
      operationId: africastalking#payment_notifier
      parameters:
      - name: payment_notifier_request_body
        in: body
        required: true
        schema:
          $ref: '#/definitions/AfricastalkingPaymentNotifierRequestBody'
          required:
          - transactionId
          - category
          - provider
          - providerChannel
          - productName
          - sourceType
          - source
          - destinationType
          - destination
          - value
          - status
          - description
          - requestMetadata
          - providerMetadata
      responses:
        "201":
          description: Created response.
          schema:
            type: string
      schemes:
      - http
  /callbacks/africastalking/sms/bulksmsoptout:
    post:
      tags:
      - africastalking
      summary: bulk_optOut_notifier africastalking
      description: Adds new SMS Bulk OptOut to our callback URL and return its ID.
      operationId: africastalking#bulk_optOut_notifier
      parameters:
      - name: bulk_optOut_notifier_request_body
        in: body
        required: true
        schema:
          $ref: '#/definitions/AfricastalkingBulkOptOutNotifierRequestBody'
      responses:
        "201":
          description: Created response.
          schema:
            type: string
      schemes:
      - http
  /callbacks/africastalking/sms/deliveryreport:
    post:
      tags:
      - africastalking
      summary: delivery_report_notifier africastalking
      description: Adds new SMS Delivery Report to our callback URL and return its ID.
      operationId: africastalking#delivery_report_notifier
      parameters:
      - name: delivery_report_notifier_request_body
        in: body
        required: true
        schema:
          $ref: '#/definitions/AfricastalkingDeliveryReportNotifierRequestBody'
      responses:
        "201":
          description: Created response.
          schema:
            type: string
      schemes:
      - http
  /callbacks/africastalking/sms/incomingmessage:
    post:
      tags:
      - africastalking
      summary: incoming_message_notifier africastalking
      description: Adds new SMS Incoming Message to our callback URL and return its ID.
      operationId: africastalking#incoming_message_notifier
      parameters:
      - name: incoming_message_notifier_request_body
        in: body
        required: true
        schema:
          $ref: '#/definitions/AfricastalkingIncomingMessageNotifierRequestBody'
      responses:
        "201":
          description: Created response.
          schema:
            type: string
      schemes:
      - http
  /callbacks/africastalking/sms/subscription:
    post:
      tags:
      - africastalking
      summary: sub_notifier africastalking
      description: Adds new SMS subscription to our callback URL and return its ID.
      operationId: africastalking#sub_notifier
      parameters:
      - name: sub_notifier_request_body
        in: body
        required: true
        schema:
          $ref: '#/definitions/AfricastalkingSubNotifierRequestBody'
      responses:
        "201":
          description: Created response.
          schema:
            type: string
      schemes:
      - http
  /callbacks/africastalking/ussd/sessions:
    post:
      tags:
      - africastalking
      summary: ussd_notifier africastalking
      description: Adds new USSD Notification to our callback URL and return its ID.
      operationId: africastalking#ussd_notifier
      produces:
      - text/plain
      parameters:
      - name: ussd_notifier_request_body
        in: body
        required: true
        schema:
          $ref: '#/definitions/AfricastalkingUssdNotifierRequestBody'
      responses:
        "201":
          description: Created response.
          schema:
            $ref: '#/definitions/AfricastalkingUssdNotifierResponseBody'
      schemes:
      - http
  /callbacks/africastalking/voice/notifications:
    post:
      tags:
      - africastalking
      summary: voice_notifier africastalking
      description: Adds new Voice Notification to our callback URL and return its ID.
      operationId: africastalking#voice_notifier
      parameters:
      - name: voice_notifier_request_body
        in: body
        required: true
        schema:
          $ref: '#/definitions/AfricastalkingVoiceNotifierRequestBody'
      responses:
        "201":
          description: Created response.
          schema:
            type: string
      schemes:
      - http
  /callbacks/africastalking/voice/transferevents:
    post:
      tags:
      - africastalking
      summary: transfer_event_notifier africastalking
      description: Adds new Event Notification to our callback URL and return its ID.
      operationId: africastalking#transfer_event_notifier
      parameters:
      - name: transfer_event_notifier_request_body
        in: body
        required: true
        schema:
          $ref: '#/definitions/AfricastalkingTransferEventNotifierRequestBody'
      responses:
        "201":
          description: Created response.
          schema:
            type: string
      schemes:
      - http
  /health:
    get:
      tags:
      - health
      summary: show health
      description: Health check endpoint.
      operationId: health#show
      produces:
      - text/plain
      responses:
        "200":
          description: OK response.
          schema:
            type: string
      schemes:
      - http
  /swagger/swagger.json:
    get:
      tags:
      - swagger
      summary: Download ../../gen/http/openapi.json
      description: JSON document containing the API swagger definition
      operationId: swagger#/swagger/swagger.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
definitions:
  AfricastalkingB2cValidationNotifierRequestBody:
    title: AfricastalkingB2cValidationNotifierRequestBody
    type: object
    properties:
      amount:
        type: number
        description: Amount - in the provided currency - that the client will receive.
        example: 500
        format: double
      currencyCode:
        type: string
        description: The 3-digist ISO format currency for the value of this transaction
        example: KES
      metadata:
        type: object
        description: A map of metadata associated with this request.
        example:
          Et exercitationem.: Inventore omnis nostrum inventore aut repellat.
        additionalProperties: true
      phoneNumber:
        type: string
        description: The phone number of the mobile subscriber receiving the B2C payment.
        example: +254711XXXYYY
      sourceIpAddress:
        type: string
        description: The IPv4 address that initiated the B2C transaction.
        example: 12.34.56.78
      transactionId:
        type: string
        description: The transaction id within Africa’s Talking.
        example: SomeTransactionID
    example:
      amount: 500
      currencyCode: KES
      metadata:
        Harum quo.: Dignissimos nam aut esse aut omnis distinctio.
        Neque atque.: Assumenda omnis exercitationem voluptatem sed nobis.
      phoneNumber: +254711XXXYYY
      sourceIpAddress: 12.34.56.78
      transactionId: SomeTransactionID
  AfricastalkingB2cValidationNotifierResponseBody:
    title: AfricastalkingB2cValidationNotifierResponseBody
    type: object
    properties:
      status:
        type: string
        example: Validated
        enum:
        - Validated
        - Failed
    example:
      status: Validated
  AfricastalkingBulkOptOutNotifierRequestBody:
    title: AfricastalkingBulkOptOutNotifierRequestBody
    type: object
    properties:
      phoneNumber:
        type: string
        description: Mobile phone number of the subscriber who opted out.
        example: Excepturi ut aut nesciunt delectus beatae.
      senderId:
        type: string
        description: Shortcode/Alphanumeric Sender ID the user opted out from.
        example: Possimus vel fugit impedit.
    example:
      phoneNumber: Omnis sunt ea eos ut est.
      senderId: Eveniet illum consequatur recusandae numquam autem ad.
  AfricastalkingC2bValidationNotifierRequestBody:
    title: AfricastalkingC2bValidationNotifierRequestBody
    type: object
    properties:
      clientAccount:
        type: string
        description: Account name used by a mobile subscriber to initiate this transaction.
        example: Ullam facilis.
      phoneNumber:
        type: string
        description: Phone number of the mobile subscriber who is initiating the C2B transaction.
        example: Recusandae enim quis.
      productName:
        type: string
        description: Identifies the Africa’s Talking Payment Product used to facilitate this transaction.
        example: Reprehenderit ut voluptatem aut molestiae.
      provider:
        type: string
        description: Payment provider that is facilitating this transaction
        example: TigoTanzania
        enum:
        - Mpesa
        - TigoTanzania
        - Athena
      providerMetadata:
        type: object
        description: Additional data received from a payment provider for a particular transaction
        example:
          Dolor quia necessitatibus tempora explicabo labore ea.: Molestiae nulla quia maxime dicta omnis eius.
          Doloremque ut voluptates voluptatem vero distinctio.: Est sint voluptatibus et commodi.
          Molestiae omnis quae consequatur quibusdam ut.: Vel sequi et enim dolorem.
        additionalProperties: true
      value:
        type: string
        description: Value being exchanged in this transaction
        example: Repellat repudiandae impedit dolores.
    example:
      clientAccount: Reiciendis et et cum impedit.
      phoneNumber: Omnis ut laudantium eligendi veniam.
      productName: Harum et.
      provider: Athena
      providerMetadata:
        Sed similique in enim perspiciatis.: Corporis earum et eius explicabo.
        Sunt quia.: Est sed.
        Voluptatem illum necessitatibus.: Nihil qui voluptatem accusamus dolorem exercitationem aut.
      value: Similique ipsum occaecati distinctio.
    required:
    - provider
    - productName
    - phoneNumber
    - value
    - providerMetadata
  AfricastalkingDeliveryReportNotifierRequestBody:
    title: AfricastalkingDeliveryReportNotifierRequestBody
    type: object
    properties:
      failureReason:
        type: string
        description: Only provided if status is Rejected or Failed.
        example: NotNetworkSubscriber
        enum:
        - InsufficientCredit
        - InvalidLinkId
        - UserIsInactive
        - UserInBlackList
        - UserAccountSuspended
        - NotNetworkSubscriber
        - UserNotSubscribedToProduct
        - UserDoesNotExist
        - DeliveryFailure
      id:
        type: string
        description: A unique identifier for each message.
        example: Voluptatem similique.
      networkCode:
        type: string
        description: A unique identifier for the Telco that handled the message.
        example: "63510"
        enum:
        - "62120"
        - "62130"
        - "62150"
        - "62160"
        - "63510"
        - "63513"
        - "63514"
        - "63902"
        - "63903"
        - "63907"
        - "63999"
        - "64002"
        - "64003"
        - "64004"
        - "64005"
        - "64007"
        - "64009"
        - "64101"
        - "64110"
        - "64111"
        - "64114"
        - "65001"
        - "65010"
        - "99999"
      phoneNumber:
        type: string
        description: Mobile phone number message was sent out to.
        example: Corporis at praesentium odio.
      retryCount:
        type: string
        description: Number of times the request to send a message to the device was retried before it succeeded or definitely failed.
        example: Incidunt sapiente error qui placeat.
      status:
        type: string
        description: The status of the message.
        example: Rejected
        enum:
        - Sent
        - Submitted
        - Buffered
        - Rejected
        - Success
        - Failed
    example:
      failureReason: InsufficientCredit
      id: Quos quas quia rerum qui.
      networkCode: "62120"
      phoneNumber: Deleniti velit.
      retryCount: Et aspernatur repellat et.
      status: Buffered
  AfricastalkingIncomingMessageNotifierRequestBody:
    title: AfricastalkingIncomingMessageNotifierRequestBody
    type: object
    properties:
      date:
        type: string
        description: The date and time when the message was received.
        example: "1972-08-02"
        format: date
      from:
        type: string
        description: The number that sent the message.
        example: A et iste eaque modi repudiandae.
      id:
        type: string
        description: The internal ID that we use to store this message.
        example: Ullam voluptas aliquam dolor eos commodi vero.
      linkId:
        type: string
        description: Parameter required when responding to an on-demand user request with a premium message.
        example: Quidem a voluptatem suscipit quas repudiandae.
      networkCode:
        type: string
        description: A unique identifier for the telco that handled the message.
        example: "64007"
        enum:
        - "62120"
        - "62130"
        - "62150"
        - "62160"
        - "63510"
        - "63513"
        - "63514"
        - "63902"
        - "63903"
        - "63907"
        - "63999"
        - "64002"
        - "64003"
        - "64004"
        - "64005"
        - "64007"
        - "64009"
        - "64101"
        - "64110"
        - "64111"
        - "64114"
        - "65001"
        - "65010"
        - "99999"
      text:
        type: string
        description: The message content.
        example: Assumenda enim fuga placeat occaecati dolore dolores.
      to:
        type: string
        description: The number to which the message was sent.
        example: Necessitatibus illo nobis occaecati aut qui.
    example:
      date: "1975-05-01"
      from: Harum molestiae dolorem.
      id: Rerum eligendi laborum doloribus blanditiis aut.
      linkId: Fugiat voluptatem reprehenderit.
      networkCode: "62130"
      text: Sit et harum qui cum totam accusantium.
      to: Dignissimos ipsa voluptatum illo.
  AfricastalkingIotNotifierRequestBody:
    title: AfricastalkingIotNotifierRequestBody
    type: object
    properties:
      payload:
        type: string
        description: The MQTT packet sent by the publishing device.
        example: "42"
      topic:
        type: string
        description: Message channel to which the message was sent by the publishing MQTT client
        example: myusername/devicegroup/sensor/id/1/temperature
    example:
      payload: "42"
      topic: myusername/devicegroup/sensor/id/1/temperature
  AfricastalkingPaymentNotifierRequestBody:
    title: AfricastalkingPaymentNotifierRequestBody
    type: object
    properties:
      category:
        type: string
        description: Category of the payment.
        example: MobileB2B
        enum:
        - BankCheckout
        - CardCheckout
        - MobileCheckout
        - MobileC2B
        - MobileB2C
        - MobileB2B
        - BankTransfer
        - WalletTransfer
        - UserStashTopup
      clientAccount:
        type: string
        description: Account name used by a mobile subscriber to initiate this transaction.
        example: Praesentium accusantium enim ab.
      description:
        type: string
        description: A detailed description of this transaction.
        example: Dolore culpa.
      destination:
        type: string
        description: Unique identifier of the party  receiving the funds for this transaction.
        example: Quidem eum iusto dignissimos.
      destinationType:
        type: string
        description: Unique identifier of the party receiving funds in this transaction (the Credit Party).
        example: PhoneNumber
        enum:
        - PhoneNumber
        - BankAccount
        - Card
        - Wallet
      productName:
        type: string
        description: Africa’s Talking Payment Product used to facilitate this transaction.
        example: Labore illum ea.
      provider:
        type: string
        description: Payment provider that facilitated this transaction.
        example: Admin
        enum:
        - Mpesa
        - Segovia
        - Flutterwave
        - Admin
        - Athena
      providerChannel:
        type: string
        description: Name or number of channel that used to facilitate this payment.
        example: Et ipsum nam minima corporis.
      providerFee:
        type: string
        description: Fee charged by a payment provider to facilitate this transaction.
        example: Ea ea et.
      providerMetadata:
        type: string
        description: Any additional data that we receive from a payment provider for a particular transaction.
        example: Architecto nam nulla voluptatem rerum et repellat.
      providerRefId:
        type: string
        description: Unique ID generated by the payment provider for this transaction.
        example: Quidem consequatur commodi quis.
      requestMetadata:
        type: string
        description: Any metadata that was sent by your application when it initiated this transaction.
        example: Eligendi explicabo porro vero.
      source:
        type: string
        description: Unique identifier of the party that is providing the funds for this transaction.
        example: Dolorum quaerat quia voluptatem explicabo reprehenderit.
      sourceType:
        type: string
        description: Type of party providing the funds for this transaction (the Debit Party).
        example: PhoneNumber
        enum:
        - PhoneNumber
        - BankAccount
        - Card
        - Wallet
      status:
        type: string
        description: The final status of this transaction
        example: Success
        enum:
        - Success
        - Failed
      transactionDate:
        type: string
        description: The date and time when a successful transaction was completed.
        example: Minima dolor.
      transactionFee:
        type: string
        description: Transaction fee charged by Africa’s Talking for this transaction.
        example: Et modi.
      transactionId:
        type: string
        description: Unique transactionId generated for every payment.
        example: Veritatis aut est in.
      value:
        type: string
        description: Value being exchanged in this transaction.
        example: Esse laboriosam asperiores vitae neque.
    example:
      category: WalletTransfer
      clientAccount: Nostrum aut.
      description: Corporis corporis dolor consequuntur beatae.
      destination: Doloremque alias voluptatem eveniet et nihil.
      destinationType: PhoneNumber
      productName: Eos debitis sit modi doloribus.
      provider: Athena
      providerChannel: Asperiores repellat.
      providerFee: Omnis adipisci nihil error.
      providerMetadata: Est unde et a necessitatibus voluptatem non.
      providerRefId: Qui sit magnam possimus ex.
      requestMetadata: Nihil minima est.
      source: Velit asperiores quibusdam qui qui.
      sourceType: Wallet
      status: Success
      transactionDate: Similique eos.
      transactionFee: Et qui similique.
      transactionId: Qui repellat inventore illo ad.
      value: Corporis sunt tenetur illum nemo neque unde.
    required:
    - transactionId
    - category
    - provider
    - providerChannel
    - productName
    - sourceType
    - source
    - destinationType
    - destination
    - value
    - status
    - description
    - requestMetadata
    - providerMetadata
  AfricastalkingStatusNotifierRequestBody:
    title: AfricastalkingStatusNotifierRequestBody
    type: object
    properties:
      requestId:
        type: string
        description: The request ID sent back as a response to the airtime send request.
        example: ATQid_SampleTxnId123
      status:
        type: string
        description: The Transaction status.
        example: Success
        enum:
        - Success
        - Failed
    example:
      requestId: ATQid_SampleTxnId123
      status: Success
  AfricastalkingSubNotifierRequestBody:
    title: AfricastalkingSubNotifierRequestBody
    type: object
    properties:
      keyword:
        type: string
        description: The product keyword that the user has subscribed or unsubscribed from.
        example: Et aut.
      phoneNumber:
        type: string
        description: Mobile phone number to subscribe or unsubscribe.
        example: Asperiores et animi at.
      shortCode:
        type: string
        description: The short code that has this product.
        example: Aliquam placeat qui saepe.
      updateType:
        type: string
        description: The type of the update.
        example: addition
        enum:
        - addition
        - deletion
    example:
      keyword: Sint voluptatem et omnis modi atque.
      phoneNumber: Eius illum beatae ipsa.
      shortCode: Qui beatae nesciunt magni numquam eius.
      updateType: addition
  AfricastalkingTransferEventNotifierRequestBody:
    title: AfricastalkingTransferEventNotifierRequestBody
    type: object
    properties:
      callSessionState:
        type: string
        example: Transferred
        enum:
        - Active
        - Transferred
        - TransferCompleted
      callTransferHangupCause:
        type: string
        example: InvalidPhoneNumber
        enum:
        - DestinationNotSupported
        - InvalidPhoneNumber
        - NoActiveClient
        - NotAllowed
      callTransferParam:
        type: string
        description: +2347XXXXXXXXX:20, (20 is the duration in seconds)
        example: Dolorum corrupti.
      callTransferState:
        type: string
        example: CalleeHangup
        enum:
        - ' Active'
        - Completed
        - CallerHangup
        - CalleeHangup
      callTransferredToNumber:
        type: string
        description: Number call was transferred to
        example: Laboriosam voluptatem.
      isActive:
        type: string
        default: "1"
        example: "1"
        enum:
        - "0"
        - "1"
      status:
        type: string
        example: Success
        enum:
        - Success
    example:
      callSessionState: Active
      callTransferHangupCause: DestinationNotSupported
      callTransferParam: Et nostrum culpa.
      callTransferState: CallerHangup
      callTransferredToNumber: Optio cupiditate incidunt quis repudiandae.
      isActive: "0"
      status: Success
  AfricastalkingUssdNotifierRequestBody:
    title: AfricastalkingUssdNotifierRequestBody
    type: object
    properties:
      networkCode:
        type: string
        description: Telco of the mobile number interacting with USSD application.
        example: Tempora iste expedita eum consectetur eligendi.
      phoneNumber:
        type: string
        description: Mobile number of the subscriber interacting with USSD application.
        example: Qui placeat asperiores amet harum corrupti.
      serviceCode:
        type: string
        description: USSD code assigned to application.
        example: Minima quia id eaque qui dolorum quisquam.
      sessionId:
        type: string
        description: A unique value generated when the session starts.
        example: Voluptas quis vero.
      text:
        type: string
        description: Shows the user input.
        example: Dolores esse quidem quod dolorem.
    example:
      networkCode: Architecto laboriosam officia vel laudantium.
      phoneNumber: Asperiores ex quam.
      serviceCode: Nulla quibusdam temporibus id quis nostrum.
      sessionId: Occaecati nisi consequuntur quisquam modi.
      text: Assumenda voluptatibus in.
  AfricastalkingUssdNotifierResponseBody:
    title: 'Mediatype identifier: ussdresponse; view=default'
    type: object
    properties:
      response:
        type: string
        description: Plain text response back to AT gateway
        example: Vel cum et atque.
    description: ussd_notifier_response_body result type (default view)
    example:
      response: Cupiditate soluta.
  AfricastalkingValidationNotifierRequestBody:
    title: AfricastalkingValidationNotifierRequestBody
    type: object
    properties:
      amount:
        type: number
        description: Amount - in the provided currency - that the client will receive.
        example: 500
        format: double
      currencyCode:
        type: string
        description: The 3-digist ISO format currency for the value of this transaction
        example: KES
      phoneNumber:
        type: string
        description: The phone number of the mobile subscriber receiving the airtime.
        example: +254711XXXYYY
      transactionId:
        type: string
        description: The transaction id within Africa’s Talking.
        example: SomeTransactionID
    example:
      amount: 500
      currencyCode: KES
      phoneNumber: +254711XXXYYY
      transactionId: SomeTransactionID
  AfricastalkingValidationNotifierResponseBody:
    title: AfricastalkingValidationNotifierResponseBody
    type: object
    properties:
      status:
        type: string
        example: Validated
        enum:
        - Validated
        - Failed
    example:
      status: Validated
  AfricastalkingVoiceNotifierRequestBody:
    title: AfricastalkingVoiceNotifierRequestBody
    type: object
    properties:
      amount:
        type: string
        description: The total cost of the call.
        example: Recusandae iure qui cumque amet.
      callSessionState:
        type: string
        description: The final status of the call.
        example: Sequi saepe quidem.
      callStartTime:
        type: string
        description: The time the call began.
        example: Est autem omnis quibusdam.
      callerCountryCode:
        type: string
        description: The code of the country the callerNumber is calling from.
        example: Totam incidunt assumenda quam amet eaque.
      callerNumber:
        type: string
        description: The phone number of the phone user in the call, in international format.
        example: +254711XXXYYY
      currencyCode:
        type: string
        description: The currency used to bill this call (e.g KES, USD, GBP).
        example: Enim non.
      destinationNumber:
        type: string
        description: Africa’s Talking phone number, in international format
        example: +254711XXXYYY
      dialDestinationNumber:
        type: string
        description: The number which a call was forwarded to if the Dial action was used.
        example: Est dolores.
      dialDurationInSeconds:
        type: string
        description: The duration of the dialed call if the Dial action was used.
        example: Nulla unde qui totam modi quo.
      dialStartTime:
        type: string
        description: The time the dial action began if the Dial action was used.
        example: Est ea error eius velit itaque error.
      direction:
        type: string
        description: Whether this is an inbound or outbound call
        example: Quibusdam eveniet eligendi a fugiat.
      dtmfDigits:
        type: string
        description: The digits that a user enters in response to a getDigits request
        example: Eaque non aut vero.
      durationInSeconds:
        type: string
        description: The duration of the call in seconds.
        example: Praesentium eius.
      hangupCause:
        type: string
        description: The reason a call could have ended
        example: UNALLOCATED_NUMBER
        enum:
        - NORMAL_CLEARING
        - CALL_REJECTED
        - NORMAL_TEMPORARY_FAILURE
        - RECOVERY_ON_TIMER_EXPIRE
        - ORIGINATOR_CANCEL
        - LOSE_RACE
        - USER_BUSY
        - NO_ANSWER
        - NO_USER_RESPONSE
        - SUBSCRIBER_ABSENT
        - SERVICE_UNAVAILABLE
        - USER_NOT_REGISTERED
        - UNALLOCATED_NUMBER
        - UNSPECIFIED
      isActive:
        type: string
        description: Lets us know whether the call is in session state
        default: "0"
        example: Dolor id vel fuga qui.
      recordingUrl:
        type: string
        description: The URL of the recording made for this call
        example: Repudiandae in sint dolorum.
      sessionId:
        type: string
        description: A unique identifier generated during each call session
        example: Aliquid eius qui ut perspiciatis provident omnis.
    example:
      amount: Et quam voluptas debitis veritatis sit.
      callSessionState: Nam iure.
      callStartTime: Neque dolores saepe tempore.
      callerCountryCode: Quos cumque pariatur ea fugiat delectus.
      callerNumber: +254711XXXYYY
      currencyCode: Pariatur nihil.
      destinationNumber: +254711XXXYYY
      dialDestinationNumber: Deserunt minima dicta illo qui aut quo.
      dialDurationInSeconds: Magnam iste quisquam accusantium enim.
      dialStartTime: Quam aut veritatis iusto sapiente veritatis.
      direction: Harum ea eum nostrum alias.
      dtmfDigits: Labore dignissimos esse rerum non minus.
      durationInSeconds: Omnis qui repellat.
      hangupCause: SUBSCRIBER_ABSENT
      isActive: Molestiae quisquam sint.
      recordingUrl: Magnam repellat harum qui.
      sessionId: Reprehenderit et eveniet.
externalDocs:
  description: Library Usage
  url: https://github.com/wondenge/at-notifiers/blob/master/README.md
